version: "3.8"

services:
  api:
    build: .
    container_name: poker-chip-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount source code for development (hot reload)
      - ./main.py:/app/main.py
      - ./api.py:/app/api.py
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8000/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Optional: Add nginx reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: poker-chip-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - api
  #   restart: unless-stopped

networks:
  default:
    name: poker-chip-network
